name: CI

on:
  workflow_dispatch: # 수동 실행만 허용 (개인 블로그에선 불필요)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.3", "3.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test.sh
